#!/bin/bash
# Author:  Chris Kasper 
# prob2
# Part of assignment 1

cd $ARCHIVE # Change directory to archive of messages
countmsg=0 # Variable to store number of msgs in current thread 
longestthread=0 # Store the largest number of msg in thread

for dir in * ; do # Start indexing through archive
	dirnumfiles=$(ls "$dir" | wc -l) # Num of msgs in thread
        if [[ $dirnumfiles != 0 ]] ; then # Check to make sure thread isn't empty
		cd "$dir" # Change directory to thread
		for mess in * ; do # Index through threads
			(( countmsg+=1 ))
		done
		cd ..
		echo "$dir" $countmsg >> $ARCHIVE/prob2.log # Logs the count of each thread
	else
		countmsg=0
		echo "$dir" $countmsg >> $ARCHIVE/prob2.log 
	fi 

	if (( $countmsg > $longestthread )) ; then # Check if current thread has the most messages
		longestthread=$countmsg
	fi
				
	countmsg=0 # Reset countmsg
done
awk '$2 == "'${longestthread}'"' prob2.log # Find directories with the most messages
rm $ARCHIVE/prob2.log # removes log file
exit 0 
