##### Makefile for accounts.py (assn4) #####
##### Author: Chris Kasper

.PHONY : build view clean

build :
	@# "Not much to do here.  I did this in Python"
	chmod +x accounts.py

view :
	@\less accounts.py

clean :
	@\rm *.pyc
